name: Documentation Website
on:
  release:
    types: [published]
jobs:
  typedoc-and-deploy:
    name: Run TypeDoc and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci --cache .npm
      - name: Generate TypeDoc static website
        run: npm run generate-docs
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
