name: Publish package
on:
  release:
    types: [published]
jobs:
  build:
    name: Build and publish on NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci --cache .npm
      - name: Create a build
        run: npm run build
      - name: Publish NPM package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
